routes/web.php
<?php

use App\Http\Controllers\EmpruntController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('layouts.home');
});
Route::resource('emprunts',EmpruntController::class);
// add adherent
Route::get('addAdherent',[EmpruntController::class,'createAdherent'])->name('addAdherent');
Route::post('addAdherent',[EmpruntController::class,'storeAdherent'])->name('addAdherent');
// login
Route::get('/login',function(){
    return view('login');
});
// logout
Route::get('/logout',function(){
    Auth::logout();
    return redirect()->to('emprunts');
})->name('logout');
Route::post('/login',[EmpruntController::class,'verify'])->name('login');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Emprunt.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Emprunt extends Model
{
    use HasFactory;
    protected $table='emprunts';
    protected $primaryKey=['CodeA','CodeL'];
    public $incrementing = false ;
    protected $keyType = 'string';

    // Relation avec la table adherents
    public function adherent()
    {
        return $this->belongsTo(Adherent::class, 'CodeA', 'CodeA');
    }
    // Relation avec la table livres
    public function livre()
    {
        return $this->belongsTo(Livre::class, 'CodeL', 'CodeL');
    }
}

app/Http/Controllers/EmpruntController.php
<?php

namespace App\Http\Controllers;

use App\Events\SendEmailEvent;
use App\Http\Middleware\q9;
use App\Models\Adherent;
use App\Models\Emprunt;
use App\Models\Livre;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Hash;

class EmpruntController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function __construct()
    {
        $this->middleware(q9::class)->only('create');
        $this->middleware('auth')->only('createAdherent');
    }
    public function index()
    {
        if(request('dateD'))
        {
            $emprunt = Emprunt::whereBetween('DateEmp', [request('dateD'), request('dateF')])
            ->orWhereBetween('DateRetour', [request('dateD'), request('dateF')])
            ->paginate(5);
        }else{
            $emprunt=Emprunt::paginate(5);
        }
        return view('Emprunts.index',['emprunts'=>$emprunt]);
    }

    /**
     * Show the form for creating a new resource.
     */
    // emprunt
    public function create()
    {
        if (Gate::allows('authenticated')) {
            return view('Emprunts.create',['adherent'=>Adherent::all(),'livre'=>Livre::all()]);
        } else {
            return redirect()->route('login');
        }
    }


    /**
     * Adherent
     */

    public function createAdherent()
    {
        return view('Emprunts.createAdh');
    }
    public function storeAdherent(Request $request)
    {
        $request->validate([
            'CodeA'=>'required',
            'NomA'=>'required|alpha',
            'AdresseA'=>'required',
            'DateInscrip'=>'required',
            'email'=>'required|email',
            'pass'=>'required|min:8',
        ]);
        $Adherent=new Adherent();
        $Adherent->CodeA=$request->CodeA;
        $Adherent->NomA=$request->NomA;
        $Adherent->AdresseA=$request->AdresseA;
        $Adherent->DateInscrip=$request->DateInscrip;
        $Adherent->email=$request->email;
        $Adherent->password=Hash::make($request->pass);
        $Adherent->save();

        // redirect with session status
        return redirect()->to('/emprunts')->with('status','Adherent ajouter avec succes');
    }

    public function verify(Request $request)
    {
        if (Auth::attempt(['email' => $request->email, 'password' => $request->pass])) {
            // l'utilisateur existe dans la table `users`
            return redirect()->to('emprunts');
        }else{
            // l'utilisateur n'existe pas dans les deux tables
            return redirect()->route('login')->with('error','email or password invalide');
        }

    }
    /**
     * End Adherent
     */


    /**
     * Store a newly created resource in storage.
     */
    // store emprunt
    public function store(Request $request)
    {
        $emprunt=new Emprunt();
        $emprunt->CodeA=$request->CodeA;
        $emprunt->CodeL=$request->CodeL;
        $emprunt->DateEmp=$request->DateEmp;
        $emprunt->DateRetour=$request->DateRetour;
        $emprunt->save();
        event(new SendEmailEvent($emprunt));
        // redirect with session status
        return redirect()->to('/emprunts')->with('status','emprunt ajouter avec succes');
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        // recuperer le id et explode parceque je concatainer les 2 id de table
        $val=explode(';',$id);
        $codeA=$val[0];
        $codeL=$val[1];
        return view('Emprunts.details',['emprunt'=>Emprunt::where('CodeA',$codeA)->where('CodeL',$codeL)->first()]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        // recuperer le id et explode parceque je concatainer les 2 id de table
        $val=explode(';',$id);
        $codeA=$val[0];
        $codeL=$val[1];
        return view('Emprunts.edit',['emprunt'=>Emprunt::where('CodeA',$codeA)->where('CodeL',$codeL)->first()]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        // recuperer le id et explode parceque je concatainer les 2 id de table
        $val = explode(';', $id);
        $codeA = $val[0];
        $codeL = $val[1];
        DB::table('emprunts')
        ->where('CodeA', $codeA)
        ->where('CodeL', $codeL)
        ->update([
            'DateEmp' => $request->DateEmp,
            'DateRetour' => $request->DateRetour
        ]);
        // redirect with session status
        return redirect()->to('/emprunts')->with('status', 'emprunt modifié avec succès');

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        // recuperer le id et explode parceque je concatainer les 2 id de table
        $val=explode(';',$id);
        $codeA=$val[0];
        $codeL=$val[1];
        Emprunt::where('CodeA',$codeA)->where('CodeL',$codeL)->delete();
        // redirect with session status
        return redirect()->to('/emprunts')->with('status','emprunt supprimer avec succes');
    }
}

resources/views/Emprunts/create.blade.php
@extends('layouts.home')

@section('content')
<center class='m-5'>
    <h1>Ajouter emprunt </h1>
</center>
<form action="{{ route('emprunts.store') }}" method='post'>
    @csrf
    <table class='ms-5'>
        <tr>
            <th>code Adherent</th>
            <th>
                <select name="CodeA" class='form-select'>
                    <option value="">Choissisez le adherent</option>
                    @forelse ($adherent as $item)
                        <option value="{{ $item->CodeA }}">{{$item->NomA}}</option>
                    @empty
                    <option value="">no adherent</option>
                    @endforelse
                </select>
            </th>
        </tr>
        <tr>
            <th>code Livre</th>
            <th>
                <select name="CodeL" class='form-select'>
                    <option value="">Choissisez livre</option>
                    <option value="{{ $item->CodeA }}">{{$item->NomA}}</option>
                    @forelse ($livre as $item)
                        <option value="{{ $item->CodeL }}">{{$item->Titre}}</option>
                    @empty
                    <option value="">no Livre</option>
                    @endforelse
                </select>
            </th>
        </tr>
        <tr>
            <th>Date Emp</th>
            <th><input class='form-control' type="date" name='DateEmp'></th>
        </tr>
        <tr>
            <th>Date Retour</th>
            <th><input class='form-control' type="date"name='DateRetour'></th>
        </tr>
        <tr>
            <th colspan="2">
                <a  href={{route('emprunts.index')}} class="btn btn-outline-info">Annuller</a>
                <button type='submit' class="btn btn-outline-primary">Ajouter</a>
            </th>
        </tr>
    </table>
</form>

@endsection

resources/views/Emprunts/createAdh.blade.php
@extends('layouts.home')

@section('content')
<center class='m-5'>
    <h1>Ajouter Adherent </h1>
</center>
<form action="{{ route('addAdherent') }}" method='post'>
    @csrf
    <table class='ms-5'>
        <tr>
            <th>code Adherent</th>
            <th>
                <input type="text" class="form-control" name='CodeA' value="{{ old('CodeA') }}">
                @error('CodeA')
                    <span class="text-danger">{{ $errors->first('CodeA') }}</span>
                @enderror
            </th>
        </tr>
        <tr>
            <th>nom Adherent</th>
            <th>
                <input type="text" class="form-control" name='NomA' value="{{ old('NomA') }}">
                @error('NomA')
                    <span class="text-danger">{{ $errors->first('NomA') }}</span>
                @enderror
            </th>
        </tr>
        <tr>
            <th>Adresse Adherent</th>
            <th>

                <input type="text" class="form-control" name='AdresseA' value="{{ old('AdresseA') }}">
                @error('AdresseA')
                    <span class="text-danger">{{ $errors->first('AdresseA') }}</span>
                @enderror
            </th>
        </tr>

        <tr>
            <th>dateInscription Adherent</th>
            <th>

                <input type="date" class="form-control" name='DateInscrip' value="{{ old('DateInscrip') }}">
                @error('DateInscrip')
                    <span class="text-danger">{{ $errors->first('DateInscrip') }}</span>
                @enderror
            </th>
        </tr>

        <tr>
            <th>email Adherent</th>
            <th>
                <input type="text" class="form-control" name='email' value="{{ old('email') }}">
                @error('email')
                    <span class="text-danger">{{ $errors->first('email') }}</span>
                @enderror

            </th>
        </tr>

        <tr>
            <th>password Adherent</th>
            <th>

                <input type="password" class="form-control" name='pass' value={{ old('pass') }}>
                @error('pass')
                    <span class="text-danger">{{ $errors->first('pass') }}</span>
                @enderror
            </th>
        </tr>
        <tr>
            <th >
                <a href={{ route('emprunts.index') }} class='btn btn-outline-info'>Annuler</a>
                <button type='submit'class='btn btn-outline-primary'>Ajouter Adherent</button>
            </th>
        </tr>
    </table>
</form>

@endsection

resources/views/Emprunts/details.blade.php
@extends('layouts.home')

@section('content')
<center class='m-5'>
    <h1>details de emprunt </h1>
</center>
<table class='ms-5'>
    <tr>
        <th>code Adherent</th>
        <th><input class='form-control' type="text" value="{{ $emprunt->CodeA }}" disabled></th>
    </tr>
    <tr>
        <th>code Livre</th>
        <th><input class='form-control' type="text" value="{{ $emprunt->CodeL }}" disabled></th>
    </tr>
    <tr>
        <th>nom Adherent</th>
        <th><input class='form-control' type="text" value={{ $emprunt->adherent->NomA }} disabled></th>
    </tr>
    <tr>
        <th>nom Livre</th>
        <th><input class='form-control' type="text" value={{ $emprunt->livre->Titre }} disabled></th>
    </tr>
    <tr>
        <th>Date Emp</th>
        <th><input class='form-control' type="text" value={{ $emprunt->DateEmp }} disabled></th>
    </tr>
    <tr>
        <th>Date Retour</th>
        <th><input class='form-control' type="text" value={{ $emprunt->DateRetour }} disabled></th>
    </tr>
    <tr>
        <th colspan="2">
            <a  href={{route('emprunts.index')}} class="btn btn-outline-info">Annuller</a>
        </th>
    </tr>
</table>

@endsection

resources/views/Emprunts/edit.blade.php
@extends('layouts.home')

@section('content')
<center class='m-5'>
    <h1>edit d emprunt </h1>
</center>
<form action="{{ route('emprunts.update',['emprunt'=>$emprunt->CodeA.';'.$emprunt->CodeL]) }}" method='post'>
    @csrf
    @method('put')
    <table class='ms-5'>
        <tr>
            <th>code Adherent</th>
            <th><input class='form-control' type="text" value="{{ $emprunt->CodeA }}" disabled></th>
        </tr>
        <tr>
            <th>code Livre</th>
            <th><input class='form-control' type="text" value="{{ $emprunt->CodeL }}" disabled></th>
        </tr>
        <tr>
            <th>nom Adherent</th>
            <th><input class='form-control' type="text" value={{ $emprunt->adherent->NomA }} disabled></th>
        </tr>
        <tr>
            <th>nom Livre</th>
            <th><input class='form-control' type="text" value={{ $emprunt->livre->Titre }} disabled></th>
        </tr>
        <tr>
            <th>Date Emp</th>
            <th><input class='form-control' type="date" value={{ $emprunt->DateEmp }} name='DateEmp'></th>
        </tr>
        <tr>
            <th>Date Retour</th>
            <th><input class='form-control' type="date" value={{ $emprunt->DateRetour }} name='DateRetour'></th>
        </tr>
        <tr>
            <th colspan="2">
                <a  href={{route('emprunts.index')}} class="btn btn-outline-info">Annuller</a>
                <button type='submit' class="btn btn-outline-warning">modifier</a>
            </th>
        </tr>
    </table>
</form>

@endsection

resources/views/Emprunts/index.blade.php
@extends('layouts.home')

@section('content')
@if(session('status'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ session('status') }}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
@endif
<div align='right' class='container my-5 '>
    <div >
        <form action="" class='d-flex'>
        <input type="date" name='dateD' class='form-control' value='{{ request("dateD") }}'><input class='form-control' type="date" name='dateF'  value='{{ request("dateF") }}'>
        <button type='submit' class='btn btn-outline-info'>Filtrer</button>
        </form>
    </div><br>
    <a href="{{ route('emprunts.create') }}" class="btn btn-outline-primary ms-5">Ajouter</a>
    <a href="{{ route('addAdherent') }}" class="btn btn-outline-primary ms-5">Ajouter Adherent</a>
</div>
<table class="table table-striped table-hover my-5 container">
    <thead>
        <tr>
            <th>Code Adherent</th><th>Code Livre</th><th>nom Adherent</th><th>nom livre</th><th>data Emprunt</th><th>date Retour</th><th>operation</th>
        </tr>
    </thead>
    <tbody>
        @forelse ($emprunts as $item)
        {{--  lister les emprunts  --}}
        <tr>
            <th>{{$item->CodeA}}</th><th>{{ $item->CodeL }}</th><th>{{ $item->adherent->NomA }}</th><th>{{ $item->livre->Titre }}</th><th>{{ $item->DateEmp }}</th><th>{{ $item->DateRetour }}</th>
            <th class='d-flex'>
                <a class="btn btn-outline-info" href={{ route('emprunts.show',['emprunt'=>$item->CodeA.';'.$item->CodeL])}}>details</a>
                <a class="btn btn-outline-warning" href={{ route('emprunts.edit',['emprunt'=>$item->CodeA.';'.$item->CodeL]) }}>update</a>
                <form action="{{ route('emprunts.destroy',['emprunt'=>$item->CodeA.';'.$item->CodeL]) }}" method="post">
                    @csrf
                    @method('delete')
                    <button class="btn btn-outline-danger " type="submit">supprimer</button>
                </form>
            </th>
        </tr>
        @empty
        {{--  si il n'exsists pas des emprunts  --}}
        <tr>
            <th colspan="7">no emprunt</th>
        </tr>
        @endforelse
    </tbody>
</table>
{{ $emprunts->links('pagination::bootstrap-5') }}

@endsection